project_id = "jkqpkbcdtbelgpuwncam"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.monthly-billing-cron]
    verify_jwt = false
    schedule = "0 6 1 * *"
